# Generated by Django 3.2.6 on 2021-09-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210902_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='nic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.localcommunity'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='username',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.localcommunity'), max_length=30, primary_key=True, serialize=False),
        ),
    ]
