# Generated by Django 3.2.6 on 2021-09-18 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210916_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='email',
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='nic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.localcommunity'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='username',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.localcommunity'), max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
