# Generated by Django 3.2.7 on 2021-10-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tracelocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracelocation',
            options={'managed': True},
        ),
    ]
