# Generated by Django 3.2.7 on 2021-10-21 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_tracelocation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('last_login', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
