# Generated by Django 3.2.6 on 2021-09-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('new_deaths', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('cumulative_deaths', models.IntegerField()),
                ('cumulative_cases', models.IntegerField()),
                ('update_timestamp', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GovernmentUpdates',
                'managed': False,
            },
        ),
    ]
