# Generated by Django 3.2.6 on 2021-10-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='nic',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='TraceLocation',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
        migrations.DeleteModel(
            name='LocalCommunity',
        ),
    ]
